### ISSUE TITLE
docker run -it --rm -e "HCLOUD_TOKEN=key" ghcr.io/mathiaspius/alpine-on-hetzner:latest gives unauthorized

### ISSUE THREAD

**Issue by dacrudg** [MathiasPius/alpine-on-hetzner#4]
Does this exist anymore? Would love to use it.
Running the above gives:

Unable to find image 'ghcr.io/mathiaspius/alpine-on-hetzner:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/mathiaspius/alpine-on-hetzner/manifests/latest": unauthorized.

Thank you

**Comment by dac11011** [comment]
Even after logging into ghcr.io still get:

# docker pull ghcr.io/mathiaspius/alpine-on-hetzner:latest
Error response from daemon: denied

Anyway you can open this back up again? Thank you!

**Comment by MathiasPius** [comment]
It should work now!

I updated the image to Alpine 3.18, Hashicorp Packer is not (yet?) available for 3.19+.

I also removed the version tag for each of the required packages, since the Alpine package repository does not keep older versions around, causing the build to fail if an older package is no longer available. This way it will always use the latest one, but of course this might mean two builds are not identical. Feel free to modify the Dockerfile to peg specific versions if you want :)

**Comment by dacrudg** [comment]
Thank you! I'm still getting this though:

docker run -it --rm -e "HCLOUD_TOKEN=key" ghcr.io/mathiaspius/alpine-on-hetzner:latest
Unable to find image 'ghcr.io/mathiaspius/alpine-on-hetzner:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/mathiaspius/alpine-on-hetzner/manifests/latest": unauthorized.

**Comment by MathiasPius** [comment]
Ah, the package was marked as private! _Now_ it should be fixed 😄

**Comment by dacrudg** [comment]
Yeah! That worked thank you

**Comment by dacrudg** [comment]
I'm getting this error:

# docker run -it --rm -e "HCLOUD_TOKEN=key" ghcr.io/mathiaspius/alpine-on-hetzner:latest
Combined configuration:
{
  "apk_tools_version": "v2.12.9",
  "apk_tools_arch": "x86_64",
  "apk_tools_url": "https://gitlab.alpinelinux.org/api/v4/projects/5/packages/generic//{{ apk_tools_version }}/{{ apk_tools_arch }}/apk.static",
  "apk_tools_checksum": "sha256:5176da3d4c41f12a08b82809aca8e7e2e383b7930979651b8958eca219815af5",
  "alpine_version": "v3.15",
  "alpine_mirror": "http://dl-cdn.alpinelinux.org/alpine",
  "alpine_repositories": [
    "main",
    "community"
  ],
  "boot_size": "+100m",
  "root_size": "0",
  "hostname": "alpine",
  "packages": {
    "openssh": "=8.8_p1-r1",
    "syslinux": "=6.04_pre1-r9",
    "linux-virt": "=5.15.16-r0",
    "cloud-init": "@community=21.4-r0"
  },
  "services": {
    "devfs": "sysinit",
    "dmesg": "sysinit",
    "mdev": "sysinit",
    "hwdrivers": "sysinit",
    "hwclock": "boot",
    "modules": "boot",
    "sysctl": "boot",
    "hostname": "boot",
    "bootmisc": "boot",
    "syslog": "boot",
    "networking": "boot",
    "mount-ro": "shutdown",
    "killprocs": "shutdown",
    "savecache": "shutdown",
    "sshd": "default"
  },
  "nameservers": [
    "185.12.64.1",
    "185.12.64.2",
    "2a01:4ff:ff00::add:1",
    "2a01:4ff:ff00::add:2"
  ],
  "sysctl": {},
  "extlinux_modules": [
    "ext4"
  ],
  "kernel_features": [
    "base",
    "ext4",
    "keymap",
    "virtio"
  ],
  "kernel_modules": [
    "ipv6",
    "af_packet"
  ],
  "default_kernel_opts": [
    "quiet"
  ],
  "chroot_commands": []
}

Starting Packer Build
alpine.hcloud.alpine: output will be in this color.

==> alpine.hcloud.alpine: Prevalidating snapshot name: alpine
==> alpine.hcloud.alpine: Creating temporary ssh key for server...
==> alpine.hcloud.alpine: Creating server...
==> alpine.hcloud.alpine: Enabling Rescue Mode...
==> alpine.hcloud.alpine: Reboot server...
==> alpine.hcloud.alpine: Using SSH communicator to connect: 1.2.3.4
==> alpine.hcloud.alpine: Waiting for SSH to become available...
==> alpine.hcloud.alpine: Error waiting for SSH: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
==> alpine.hcloud.alpine: Destroying server...
==> alpine.hcloud.alpine: Deleting temporary ssh key...
Build 'alpine.hcloud.alpine' errored after 2 minutes 9 seconds: Packer experienced an authentication error when trying to connect via SSH. This can happen if your username/password are wrong. You may want to double-check your credentials as part of your debugging process. original error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**Comment by MathiasPius** [comment]
I'll be honest, it's been ages since I worked on this so I don't really have any insights into what might be going wrong. If I were you, I'd start by just trying to running packer directly, and seeing if that works

**Comment by dacrudg** [comment]
I got a little farther now.  Any idea on this?
Thanks for any help

    alpine.hcloud.alpine: TASK [Gathering Facts] *********************************************************
    alpine.hcloud.alpine: ok: [localhost]
    alpine.hcloud.alpine:
    alpine.hcloud.alpine: TASK [cache apk tools] *********************************************************
    alpine.hcloud.alpine: fatal: [localhost]: FAILED! => {"changed": false, "checksum_dest": null, "checksum_src": "8086b8ad1fc1c82264927cb6ddd2aec959d600da", "dest": "/cache/apk.static", "elapsed": 1, "msg": "Destination /cache does not exist", "src": "/root/.ansible/tmp/ansible-tmp-1718032423.0272787-1594408-84183332871312/tmp7h32uaii", "url": "https://gitlab.alpinelinux.org/api/v4/projects/5/packages/generic//v2.12.9/x86_64/apk.static"}
    alpine.hcloud.alpine:
    alpine.hcloud.alpine: PLAY RECAP *********************************************************************
    alpine.hcloud.alpine: localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
    alpine.hcloud.alpine:
==> alpine.hcloud.alpine: Provisioning step had errors: Running the cleanup provisioner, if present...
==> alpine.hcloud.alpine: Destroying server...
==> alpine.hcloud.alpine: Deleting temporary SSH key...
Build 'alpine.hcloud.alpine' errored after 1 minute 11 seconds: Error executing Ansible: Non-zero exit status: exit status 2

**Comment by dacrudg** [comment]
I fixed the above by creating the directory manually.
Now getting farther to this:

    alpine.hcloud.alpine: TASK [install requisite packages] **********************************************
    alpine.hcloud.alpine: changed: [default] => (item={'key': 'openssh', 'value': '=8.8_p1-r1'})
    alpine.hcloud.alpine: changed: [default] => (item={'key': 'syslinux', 'value': '=6.04_pre1-r9'})
    alpine.hcloud.alpine: failed: [default] (item={'key': 'linux-virt', 'value': '=5.15.16-r0'}) => {"ansible_loop_var": "item", "changed": true, "cmd": "chroot /mnt apk add --no-cache linux-virt=5.15.16-r0\n", "delta": "0:00:00.288107", "end": "2024-06-10 17:19:43.155805", "item": {"key": "linux-virt", "value": "=5.15.16-r0"}, "msg": "non-zero return code", "rc": 1, "start": "2024-06-10 17:19:42.867698", "stderr": "ERROR: unable to select packages:", "stderr_lines": ["ERROR: unable to select packages:"], "stdout": "fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz\nfetch http://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz\n  linux-virt-5.15.140-r0:\n    breaks: world[linux-virt=5.15.16-r0]", "stdout_lines": ["fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz", "fetch http://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz", "  linux-virt-5.15.140-r0:", "    breaks: world[linux-virt=5.15.16-r0]"]}
    alpine.hcloud.alpine: changed: [default] => (item={'key': 'cloud-init', 'value': '@community=21.4-r0'})
    alpine.hcloud.alpine:
    alpine.hcloud.alpine: PLAY RECAP *********************************************************************
    alpine.hcloud.alpine: default                    : ok=12   changed=12   unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
    alpine.hcloud.alpine: localhost                  : ok=3    changed=2    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
    alpine.hcloud.alpine:
==> alpine.hcloud.alpine: Provisioning step had errors: Running the cleanup provisioner, if present...
==> alpine.hcloud.alpine: Destroying server...
==> alpine.hcloud.alpine: Deleting temporary SSH key...
Build 'alpine.hcloud.alpine' errored after 1 minute 30 seconds: Error executing Ansible: Non-zero exit status: exit status 2

**Comment by dacrudg** [comment]
OK, I got this working with no errors.  Says the snapshot completed and everything.
But when I login to Hetzner, provision from snapshot, that snapshot doesn't exist? I don't see any alpine snaphots or anything in my Hetzner environment.

**Comment by dacrudg** [comment]
Nevermind, found it!

**Comment by MathiasPius** [comment]
Glad you got it to work, sorry I couldn't be of more help!

How did you end up resolving the problem? Just in case someone else stumbles upon this thread in the future :)

**Comment by dacrudg** [comment]
I had to make ansible create the /cache directory in the beginning.
